services:
  postgres:
    image: postgres:15-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  fudy:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app:delegated
      - /app/node_modules
